name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: qwiklabs-gcp-01-17a428d45b63
          export_default_credentials: true

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag europe-west4-docker.pkg.dev/qwiklabs-gcp-01-17a428d45b63/notely-ar-repo/notely:latest .